module.exports = {
    // CropIDS are for the integer ID's for different crops in SQL tile table
    ProduceIDs: {
        carrot_seeds: 1,
        melon_seeds: 2,
        cauliflower_seeds: 3,
        pumpkin_seeds: 4,
        yam_seeds: 5,
        beet_seeds: 6,
        parsnip_seeds: 7,
        bamboo_seeds: 8,
        hops_seeds: 9,
        corn_seeds: 10,
        potato_seeds: 11,
        blueberry_seeds: 12,
        grape_seeds: 13,
        oats_seeds: 14,
        strawberry_seeds: 15
    },
    // CropNames is the exact inverse of above, to easily get names from id's, first index is null for indexing
    ProduceNameFromID: [null, "carrot_seeds", "melon_seeds", "cauliflower_seeds", "pumpkin_seeds", "yam_seeds",
        "beet_seeds", "parsnip_seeds", "bamboo_seeds", "hops_seeds", "corn_seeds", "potato_seeds",
        "blueberry_seeds", "grape_seeds", "oats_seeds", "strawberry_seeds"],
    // Maps seeds to what crop they make, key is seed name, value is array of [crop_name, qty per harvest, total_harvests] produced
    SeedCropMap: {
        carrot_seeds: ["carrot", 3, 2],
        melon_seeds: ["melon", 1, 1],
        cauliflower_seeds: ["cauliflower", 1, 1],
        pumpkin_seeds: ["pumpkin", 1, 1],
        yam_seeds: ["yam", 4, 3],
        beet_seeds: ["beet", 4, 3],
        parsnip_seeds: ["parsnip", 2, 1],
        bamboo_seeds: ["bamboo", 5, 4],
        hops_seeds: ["hops", 1, 3],
        corn_seeds: ["corn", 1, 3],
        potato_seeds: ["potato", 3, 3],
        blueberry_seeds: ["blueberry", 6, 5],
        grape_seeds: ["grape", 6, 5],
        oats_seeds: ["oats", 4, 4],
        strawberry_seeds: ["strawberry", 3, 4]
    },
    // Fixed prices is for prices of things you buy from the game (seeds, animals)
    // 
    Fixed_Prices: {
        carrot_seeds: 30,
        melon_seeds: 120,
        cauliflower_seeds: 120,
        pumpkin_seeds: 120,
        yam_seeds: 40,
        beet_seeds: 50,
        parsnip_seeds: 50,
        bamboo_seeds: 40,
        hops_seeds: 50,
        corn_seeds: 50,
        potato_seeds: 40,
        blueberry_seeds: 80,
        grape_seeds: 80,
        oats_seeds: 15,
        strawberry_seeds: 45
    },
    // 
    Init_Market_Prices: {
        carrot: 17,
        melon: 340,
        cauliflower: 300,
        pumpkin: 340,
        yam: 50,
        beet: 35,
        parsnip: 25,
        bamboo: 10,
        hops: 15,
        corn: 20,
        potato: 15,
        blueberry: 10,
        grape: 12,
        oats: 5,
        strawberry: 20,

        
        cow_milk: 100,
        chicken_egg: 60,
        duck_egg: 80,
        quail_egg: 100,
        yak_milk: 200,
        sheep_wool: 140,
        goat_milk: 80,
        ostrich_egg: 500,
        llama_wool: 200,
        kiwi_egg: 400,
    },
    // key: type, array is [building, cost]
    AnimalTypes: {
        "cow": ['barn', 300],
        "chicken": ['coop', 175],
        "duck": ['coop', 400],
        "quail": ['coop', 500],
        "yak": ['barn', 600],
        "sheep": ['barn', 400],
        "goat": ['barn', 500],
        "ostrich": ['coop', 900],
        "llama": ['barn', 700],
        "kiwi": ['coop', 800],
    },
    // default time per collect in seconds
    // [ display name , more details ]
    InventoryDescriptions: {
        carrot_seeds: ["Carrot Seeds", "High yield, medium growth time"],
        melon_seeds: ["Melon Seeds", "Low yield, very long growth time"],
        corn_seeds: ["Corn Seeds", "Medium yield, medium growth time"],
        cauliflower_seeds: ["Cauliflower Seeds", "Low yield, long growth time"],
        pumpkin_seeds: ["Pumpkin Seeds", "Low yield, very long growth time"],
        yam_seeds: ["Yam Seeds", "Medium yield, medium growth time"],
        beet_seeds: ["Beet Seeds", "Medium yield, medium growth time"],
        parsnip_seeds: ["Parsnip Seeds", "Medium yield, medium growth time"],
        bamboo_seeds: ["Bamboo Seeds", "High yield, short growth time"],
        hops_seeds: ["Hops Seeds", "High yield, medium growth time"],
        potato_seeds: ["Potato Seeds", "High yield, medium growth time"],
        blueberry_seeds: ["Blueberry Seeds", "High yield, high initial growth time with short regrowth"],
        grape_seeds: ["Grape Seeds", "High yield, high initial growth time with short regrowth"],
        oats_seeds: ["Oat Seeds", "High yield, short growth time"],
        strawberry_seeds: ["Strawberry Seeds", "Medium yield, long growth time"],
        cow: ["Cow", "Produces milk"],
        chicken: ["Chicken", "Produces eggs"],
        duck: ["Duck", "Produces duck eggs"],
        quail: ["Quail", "Produces quail eggs"],
        yak: ["Yak", "Produces yak milk"],
        sheep: ["Sheep", "Produces sheep wool"],
        goat: ["Goat", "Produces goat milk"],
        ostrich: ["Ostrich", "Produces ostrich eggs"],
        llama: ["Llama", "Produces llama wool"],
        kiwi: ["Kiwi", "Produces kiwi egg"],
        carrot: ["Carrot", "Flora"],
        melon: ["Melon", "Flora"],
        cauliflower: ["Cauliflower", "Flora"],
        pumpkin: ["Pumpkin", "Flora"],
        yam: ["Yam", "Flora"],
        beet: ["Beet", "Flora"],
        parsnip: ["Parsnip", "Flora"],
        bamboo: ["Bamboo", "Flora"],
        hops: ["Hops", "Flora"],
        corn: ["Corn", "Flora"],
        potato: ["Potato", "Flora"],
        blueberry: ["Blueberries", "Flora"],
        grape: ["Grapes", "Flora"],
        oats: ["Oats", "Flora"],
        strawberry: ["Strawberry", "Flora"],
        cow_milk: ["Cow Milk", "Produce"],
        chicken_egg: ["Chicken Egg", "Produce"],
        duck_egg: ["Duck Egg", "Produce"],
        quail_egg: ["Quail Egg", "Produce"],
        yak_milk: ["Yak Milk", "Produce"],
        sheep_wool: ["Sheep Wool", "Produce"],
        goat_milk: ["Goat Milk", "Produce"],
        ostrich_egg: ["Ostrich Egg", "Produce"],
        llama_wool: ["Llama Wool", "Produce"],
        kiwi_egg: ["Kiwi Egg", "Produce"],
        Balance: ["Money", "Currency"]
    },
    // For each permit type, what crops and animals it permits
    Permits: {
        "deluxeCrops": ['grape_seeds', 'bamboo_seeds', 'hops_seeds'],
        "exoticAnimals": ['quail', 'llama', 'kiwi'],
    },
    // Luxury goods have a artifical bonus in market prices of 5% and higher floors, usually from deluxe/exotics or things that need permits / higher costs
    LuxuryGoods: ['grape', 'bamboo', 'hops'],
    // What crops are unlocked at each XP threshold
    Levels: {
        0: ['carrot_seeds', 'oats_seeds', 'cauliflower_seeds', 'corn_seeds', 'potato_seeds', 'parsnip_seeds', 'cow', 'chicken', 'grape_seeds', 'bamboo_seeds', 'hops_seeds', 'quail', 'kiwi'],
        200: ['pumpkin_seeds', 'yam_seeds', 'beet_seeds', 'duck', 'sheep'],
        500: ['melon_seeds', 'llama', 'goat'],
        1000: ['blueberry_seeds', 'ostrich', 'quail'],
        2000: ['strawberry_seeds', 'yak']
    },
    // the xp you get from harvesting/collecting this thing once total, not per item (ex: total for grape tile harvest, not per grape)
    XP: {
        carrot: 8,
        melon: 800,
        cauliflower: 600,
        pumpkin: 800,
        yam: 15,
        beet: 12,
        parsnip: 8,
        bamboo: 4,
        hops: 10,
        corn: 5,
        potato: 10,
        blueberry: 10,
        grape: 12,
        oats: 1,
        strawberry: 30,
        cow_milk: 25,
        chicken_egg: 15,
        duck_egg: 20,
        quail_egg: 25,
        yak_milk: 50,
        sheep_wool: 35,
        goat_milk: 20,
        ostrich_egg: 125,
        llama_wool: 50,
        kiwi_egg: 100,
    }
}