module.exports = {
  seedsFromID: [
    null,
    "carrot_seeds",
    "melon_seeds",
    "cauliflower_seeds",
    "pumpkin_seeds",
    "yam_seeds",
    "beet_seeds",
    "parsnip_seeds",
    "bamboo_seeds",
    "hops_seeds",
    "corn_seeds",
    "potato_seeds",
    "blueberry_seeds",
    "grape_seeds",
    "oats_seeds",
    "strawberry_seeds",
  ],
  seedCropMap: {
    carrot_seeds: "carrot",
    melon_seeds: "melon",
    cauliflower_seeds: "cauliflower",
    pumpkin_seeds: "pumpkin",
    yam_seeds: "yam",
    beet_seeds: "beet",
    parsnip_seeds: "parsnip",
    bamboo_seeds: "bamboo",
    hops_seeds: "hops",
    corn_seeds: "corn",
    potato_seeds: "potato",
    blueberry_seeds: "blueberry",
    grape_seeds: "grape",
    oats_seeds: "oats",
    strawberry_seeds: "strawberry",
  },
  XP: {
    carrot: 4,
    melon: 10,
    cauliflower: 10,
    pumpkin: 10,
    yam: 5,
    beet: 4,
    parsnip: 4,
    bamboo: 2,
    hops: 4,
    corn: 3,
    potato: 4,
    blueberry: 2,
    grape: 2,
    oats: 3,
    strawberry: 5,

    cow_milk: 8,
    chicken_egg: 6,
    duck_egg: 8,
    quail_egg: 8,
    yak_milk: 9,
    sheep_wool: 7,
    goat_milk: 7,
    ostrich_egg: 12,
    llama_wool: 12,
    kiwi_egg: 12,
  },
};
